// @flow

import '../analytics/middleware';
import '../base/conference/middleware';
import '../base/config/middleware';
import '../base/known-domains/middleware';
import '../base/lastn/middleware';
import '../base/lib-jitsi-meet/middleware';
import '../base/logging/middleware';
import '../base/media/middleware';
import '../base/net-info/middleware';
import '../base/participants/middleware';
import '../base/redux/middleware';
import '../base/responsive-ui/middleware';
import '../base/settings/middleware';
import '../base/sounds/middleware';
import '../base/testing/middleware';
import '../base/tracks/middleware';
import '../base/user-interaction/middleware';
import '../conference/middleware';
import '../connection-indicator/middleware';
import '../deep-linking/middleware';
import '../device-selection/middleware';
import '../display-name/middleware';
import '../etherpad/middleware';
import '../filmstrip/middleware';
import '../large-video/middleware';
import '../notifications/middleware';
import '../overlay/middleware';
import '../rejoin/middleware';
import '../rtcstats/middleware';
import '../toolbox/middleware';
import '../video-layout/middleware';
import '../video-quality/middleware';
import '../videosipgw/middleware';

import './middleware';
